matplo/pyjetty

- pyjetty/alice_analysis/process/base/common_utils.py
(This shouldn't have any effect on current behavior)
> update grooming setting utils to allow multiple groomers

- pyjetty/alice_analysis/slurm/utils/james/plot_file_sizes.py
> add script to plot histogram of file sizes from a file list

- pyjetty/alice_analysis/process/base/process_io.py
This commit removes class members from the IO class which have no actual need to be class members, in order to reduce memory consumption. 
This results in reduction of memory consumption by a factor up to ~2.
@matplo @ezradlesser
> remove unnecessary class members from IO class

- pyjetty/alice_analysis/generation/hepmc2antuple_tn.py
Copy of Mateusz's script from sandbox, I just added an option `--no-progress-bar` for slurm usage.
@matplo @ezradlesser
> add hepmc converter to alice_analysis

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
@ezradlesser 
- Fix name of Soft Drop tagging histogram, to not include reg param in name
- Fix obs_label vs. obs_setting
- Move certain print statements and histograms to be produced only if self.debug_level > 0
> several minor fixes for automated reg param determination

- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
@ezradlesser 
This adds plot of the correlation coefficients (related to covariance matrix) of the statistical uncertainties. 
However at the moment it just plots the correlation of a global bin index, i.e. a global 2D correlation rather than the full 4D correlation chopped up into 2D correlations for each pt bin...needs a little work to figure out how to map the 2D global bin index to the 4D bin index. I didn't see any simple way to get this from RooUnfold...but I didn't dig too deep, maybe you will have better luck :)
> add first draft of correlation coefficient plot

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
> revert copying of prior response, since prior rescaling happens in rebin

- pyjetty/alice_analysis/analysis/user/substructure/analysis_utils_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
(should have no impact on pp analyses)
> add Rmax to naming convention in PbPb case

- pyjetty/alice_analysis/analysis/user/substructure/analysis_utils_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
(should have no effect on pp analyses)
> add Rmax systematic variations (and move Rmax from obs_label to hist names)

- pyjetty/alice_analysis/analysis/user/substructure/analysis_utils_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
(should have no effect on pp analyses)
> add prong matching RM to systematics list

- pyjetty/alice_analysis/analysis/user/substructure/analysis_utils_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
(has no effect on pp analyses)
> add thermal closure test to analysis

- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
(minor plotting change)
@ezradlesser
> plot refolding test over full pt-det range

- pyjetty/alice_analysis/analysis/base/analysis_utils.py
- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
(previously this was done with a pure MC correction)
@ezradlesser this should have no effect on non-SoftDrop analyses
> Include SD untagged jets in unfolding

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
@ezradlesser This is just saving the final selected reg param into a text file for convenience. We could also e.g. generate a tex table automatically, for example. Feel free to modify as desired.
> add reg param to logfile

- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
Enable code to be run without grooming.
> Allow new edits to work without grooming

- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
(no effect on non-groomed analyses)
> fix binning arrays for SD case

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
@ezradlesser This is just for convenience of evaluating the tests, and for ease of putting them in the AN (can just copy the folder to overleaf, without having to change the figure paths in tex).
> copy unfolding tests for final reg param into separate folder

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
Did basic check that this works -- @ezradlesser let me know if any problems.
The code here is growing a bit messy -- we should clean it up after HP.
> combine prior and subtraction systematics into a single systematic each

- pyjetty/alice_analysis/process/base/process_io.py
This commit adds an option to the IO class to use the `ev_id_ext` parameter when defining the unique id combination to identify an event. This is needed for certain recent productions.
This has no effect on the 5 TeV pp data or MC.
And no effect on the PbPb data -- but it does affect one of the recent re-productions of MC anchored to PbPb.
> add option to include ev_id_ext

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
> fix legend label in systematics plot

- pyjetty/alice_analysis/analysis/base/analysis_utils.py
- pyjetty/alice_analysis/analysis/user/ang_pp/run_analysis_ang.py
Added changes necessary for rebinning histograms for comparisons to previous preliminary results.
Some changes were made in analysis_utils.py by adding an optional parameter which shouldn't affect any prior code if not used directly.
> Previous preliminary comparisons

- pyjetty/alice_analysis/analysis/user/ang_pp/run_analysis_ang.py
- pyjetty/alice_analysis/process/base/process_io_pyth.py
- pyjetty/alice_analysis/process/user/ang_pp/ang_data.py
- pyjetty/alice_analysis/process/user/ang_pp/ang_fs.py
- pyjetty/alice_analysis/process/user/ang_pp/ang_mc.py
- pyjetty/alice_analysis/process/user/ang_pp/ang_pyth.py
- pyjetty/alice_analysis/process/user/ang_pp/helpers.py
- pyjetty/alice_analysis/process/user/ang_pp/pythia_parton_hadron.py
- pyjetty/alice_analysis/slurm/sbatch/ang/pythia_gen/ang_slurm_pythia.sh
- pyjetty/eic/pythia_parton_hadron.py
For generation of new PYTHIA events and creating response matrices
> Pythia at parton/hadron/charged levels & RM generation

- cpptools/src/fjtools/fjtools.cxx
- cpptools/src/fjtools/fjtools.hh
- pyjetty/alice_analysis/analysis/user/ang_pp/theory_comp.py
- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin1.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin2.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin3.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin1.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin2.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin3.yaml
- pyjetty/alice_analysis/process/user/ang_pp/ang_mc.py
- pyjetty/alice_analysis/slurm/sbatch/ang/ang_slurm_LHC18b8.sh
- pyjetty/alice_analysis/slurm/sbatch/ang/treff/ang_slurm_LHC18b8_treff.sh
- pyjetty/alice_analysis/slurm/utils/ang/merge_LHC18b8.sh
- pyjetty/alice_analysis/slurm/utils/ang/merge_data.sh
- pyjetty/alice_analysis/slurm/utils/ang/merge_mc.sh
Still requires
1) Creating and returning RooUnfoldResponse object if desired
2) Implementing fill_rebinned_thn in N dimensions (though this is not required for any current usage, to my knowledge)
3) Scaling prior by user function of observable axis in fill_rebinned_thn if desired:
-- maybe we should implement several different possible scaling functions for this axis, and the user passes a string to select one of them?
> Implementing THn rebinning on cpp side

- cpptools/src/rutil/rutil.cxx
- cpptools/src/rutil/rutil.hh
- pyjetty/alice_analysis/analysis/user/substructure/roounfold_obs.py
Rebinning should now work in C++ -- I just essentially reverted to the original way of specifying binnings, since something was mixed up. 
Did some simple testing and all looks good -- but please check that you reproduce results @ezradlesser
> fix axes for rebinning, and set c++ to default

- cpptools/src/rutil/rutil.cxx
- pyjetty/alice_analysis/analysis/user/ang_pp/plot_angularity_theory_figures.py
- pyjetty/alice_analysis/analysis/user/ang_pp/run_analysis_ang.py
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin1.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin2.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin3.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.2_ptbin4.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin1.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin2.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin3.yaml
- pyjetty/alice_analysis/config/ang/angularity_R0.4_ptbin4.yaml
Code to create groomed angularity theory comparison plots. Some formatting remains to be finalized
> Angularity theory plotting updates

- pyjetty/alice_analysis/analysis/user/substructure/run_analysis.py
@ezradlesser can you take a look at this, since it builds on some of your functionality? I did some tests but want to make sure it looks good to you before merging.
> extend maxbin functionality to include minbin as well
